<a href="https://colab.research.google.com/github/Kavya-1708/python_basics/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Create a 3*3 array with values ranging from 2 to 10.

In [1]:
import numpy as np

# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)

# Display the matrix
print("3x3 Matrix:")
print(matrix)

3x3 Matrix:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Q2. Create a NumPy array having user input values and convert the integer type to the float type of the elements of the array. For instance: Original array [1,2,3,4] Array converted to a float type : [1. 2. 3. 4.]

In [2]:
import numpy as np

# Take user input for the array elements
user_input = input("Enter the elements of the array separated by spaces: ")

# Convert the input string to a list of integers
original_array = np.array([int(x) for x in user_input.split()])

# Convert the integer array to float type
float_array = original_array.astype(float)

# Display the original and converted arrays
print("Original array:", original_array)
print("Array converted to float type:", float_array)

Enter the elements of the array separated by spaces: 1 2 3 4 
Original array: [1 2 3 4]
Array converted to float type: [1. 2. 3. 4.]


Q3. Write a NumPy program to append values to the end of the array. For instance: Original array: [10,20,30]. After that, append values to the end of the array : [10 20 30 40 50 60 70 80 90]

In [3]:
import numpy as np

# Original array
original_array = np.array([10, 20, 30])

# Values to append
values_to_append = [40, 50, 60, 70, 80, 90]

# Append values to the array
new_array = np.append(original_array, values_to_append)

# Display the result
print("Original array:", original_array)
print("Array after appending values:", new_array)

Original array: [10 20 30]
Array after appending values: [10 20 30 40 50 60 70 80 90]


Q4. Create two NumPy arrays and add the elements of both the arrays and store the result in sumArray.

In [4]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Add the elements of both arrays
sumArray = np.add(array1, array2)

# Display the result
print("First Array:", array1)
print("Second Array:", array2)
print("Sum of Arrays:", sumArray)

First Array: [1 2 3]
Second Array: [4 5 6]
Sum of Arrays: [5 7 9]


Q5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1.

Perform the following tasks -

a. Extract the 1st row from the array.

b. Extract the last element from the array.

In [5]:
import numpy as np

# Create a 3x3 array with values ranging from 10 to 90 (interval of 10)
array1 = np.arange(10, 100, 10).reshape(3, 3)

# Perform the tasks
# a. Extract the 1st row from the array
first_row = array1[0, :]

# b. Extract the last element from the array
last_element = array1[-1, -1]

# Display the results
print("3x3 Array:")
print(array1)
print("\n1st Row:", first_row)
print("Last Element:", last_element)

3x3 Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

1st Row: [10 20 30]
Last Element: 90
