<a href="https://colab.research.google.com/github/Kavya-1708/python_basics/blob/main/casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Create a function that dimensions as tuples e.g. (3,3) and a numeric value and returns a NumPy array of the given dimension filled with the given value. eg : solve((3,3),5) will return
[
  [ 5, 5, 5 ],
  [ 5, 5, 5 ],
  [ 5, 5, 5]
]
    

In [1]:
import numpy as np

def solve(dimensions, value):
    """
    Create a NumPy array with given dimensions, filled with the specified value.

    Parameters:
    dimensions (tuple): Shape of the array (e.g., (3,3))
    value (numeric): Value to fill the array with

    Returns:
    numpy.ndarray: Array filled with the given value
    """
    return np.full(dimensions, value)

# Example usage:
result = solve((3, 3), 5)
print(result)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


Q2. Create a method that takes n NumPy arrays of the same dimensions, sums them and returns the answer.

In [2]:
import numpy as np

def sum_arrays(*arrays):
    """
    Sum multiple NumPy arrays element-wise.

    Parameters:
    *arrays: Variable-length NumPy arrays (all must have the same shape)

    Returns:
    numpy.ndarray: Summed array
    """
    return np.sum(arrays, axis=0)  # Perform element-wise sum

# Example usage:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15], [16, 17, 18]])

result = sum_arrays(array1, array2, array3)
print("Summed Array:\n", result)

Summed Array:
 [[21 24 27]
 [30 33 36]]


Q3.  Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix, e.g: [ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] top_left_sub_matrix (matrix, 2, 2) -> should return: [ [1, 2] [4, 5] ]



In [3]:
def top_left_sub_matrix(matrix, N, M):
    return matrix[:N, :M]

# Example usage:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(top_left_sub_matrix(matrix, 2, 2))

[[1 2]
 [4 5]]


Q4. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the bottom-right N X M sub matrix, e.g: [ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed) [ [5, 6] [8, 9] ]

In [4]:
def bottom_right_sub_matrix(matrix, N, M):
    return matrix[-N:, -M:]

# Example usage:
print(bottom_right_sub_matrix(matrix, 2, 2))

[[5 6]
 [8 9]]


Q5. Given a 1 D NumPy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values: [1, 1, 1] solution(arr) -> should return : {'mean': 1.0, 'std_dev': 0.0}



In [5]:
def solution(arr):
    return {"mean": np.mean(arr), "std_dev": np.std(arr)}

# Example usage:
print(solution(np.array([1, 1, 1])))

{'mean': np.float64(1.0), 'std_dev': np.float64(0.0)}
